@startuml

package StorageSystem {
	class Motr
	class MotrClient
}


package ApplicationProc {
	class Datatypes
	class Progress
	class Layout
	class "Motr Backend" as Backend
}

class "Performance Model" as Performance
class "Site Configuration" as SiteConfig


Motr <-- MotrClient




MotrClient --> Performance: provides
MotrClient --> SiteConfig: provides


Backend --> MotrClient

Backend <-- Progress

Datatypes --> Progress

Layout <--> Performance


Layout <--> SiteConfig
Layout <-- Progress




@enduml
