@startuml

node App1 {
	node Proc11 {
	control "ESDM Progress" as progress11
	control "ESDM MotrClient Instance" as m0client11
	control "ESDM MotrSrvMgmt" as mgmt11
	}

	node Proc12 {
	control "ESDM Progress" as progress12
	control "ESDM MotrClient Instance" as m0client12
	control "ESDM MotrSrvMgmt" as mgmt12
	}
}

progress11 --> m0client11 : use
progress12 --> m0client12 : use

node App2 {
	node Proc21 {
	control "ESDM Progress" as progress21
	control "ESDM MotrClient Instance" as m0client21
	control "ESDM MotrSrvMgmt" as mgmt21
	}

	node Proc22 {
	control "ESDM Progress" as progress22
	control "ESDM MotrClient Instance" as m0client22
	control "ESDM MotrSrvMgmt" as mgmt22
	}
}
progress21 --> m0client21 : use
progress22 --> m0client22 : use

storage MotrStorageSystem {
	control MotrConfd
	control MotrRMS
	control MotrIOS
}

m0client11 <--> MotrConfd
m0client11 <--> MotrRMS
m0client11 <--> MotrIOS

m0client12 <--> MotrConfd
m0client12 <--> MotrRMS
m0client12 <--> MotrIOS

m0client21 <--> MotrConfd
m0client21 <--> MotrRMS
m0client21 <--> MotrIOS


m0client22 <--> MotrConfd
m0client22 <--> MotrRMS
m0client22 <--> MotrIOS

mgmt11 --> MotrConfd
mgmt12 --> MotrConfd
mgmt21 --> MotrConfd
mgmt22 --> MotrConfd

@enduml
