@startuml

participant "App/Process" as proc
participant "ESDM API" as ESDM

participant "ESDM Progress" as progress
participant "ESDM Layout" as layout

participant "Motr Backend" as backend
participant "Motr Storage" as storage


proc -> ESDM: read
ESDM -> progress: read
progress -> layout: lookup
layout -> progress: Motr identifier of metadata

progress -> backend: GET metadata key-values
backend -> storage:  MotrClient index operations
backend <- storage:  MotrClient reply
progress <- backend: return with metadata

progress -> backend: subrequest to object for raw data
progress -> backend: subrequest to object for raw data

...

backend -> storage:  MotrClient object operations
backend <- storage:  MotrClient reply

...

progress <- backend: return with data
progress <- backend: return with data

progress -> progress: filling data

ESDM <- progress: return
proc <- ESDM: return



@enduml
