FROM centos

# Requirements and dependencies easily obtained with the distribution
RUN dnf -y install make automake gcc gcc-c++ cmake git glib2 glib2-devel jansson jansson-devel mpich-devel

# Requirements and ESDM compilation from source
WORKDIR "/data"
#RUN git clone https://github.com/ESiWACE/esdm.git
#RUN git clone https://github.com/ESiWACE/esdm-netcdf.git
