MERO_DIR=/mero/target

AM_CPPFLAGS = -D_REENTRANT -D_GNU_SOURCE -DM0_INTERNAL='' -DM0_EXTERN=extern -iquote ${MERO_DIR} -iquote '.' -DM0_SRC_DIR=${MERO_DIR} -I${MERO_DIR}/include -I${MERO_DIR}/include/mero -I../../include -fno-common -Wall -Werror -Wno-attributes -fno-strict-aliasing -fno-omit-frame-pointer -g -O2

AM_LDFLAGS = -rdynamic -pthread -Wl,-rpath -Wl,/usr/local/lib
AM_LIBS = ${MERO_DIR}/lib/libmero.so -lm -lpthread -laio -lrt -lyaml -luuid ${MERO_DIR}/lib/libgf_complete.so -ldl ${MERO_DIR}/lib/libmero-ut.so ${MERO_DIR}/lib/libmero-net-test.so ${MERO_DIR}/lib/libmero-xcode-ff2c.so

HDR = clovis.h
SRC = clovis.c
OBJ = clovis.o
TGT = clovis_test

all: ${TGT}
.PHONY: all

${OBJ}:${SRC} 
	gcc ${AM_CPPFLAGS} ${AM_CFLAGS} -c -o ${OBJ} ${SRC}

test.o: test/test.c
	gcc ${AM_CPPFLAGS} ${AM_CFLAGS} -c -o test.o test/test.c

${TGT}:${OBJ} test.o
	gcc ${AM_CFLAGS} ${AM_LDFLAGS} -o ${TGT} ${OBJ} test.o ${AM_LIBS}

clean:
	rm -f ${OBJ} ${TGT} test.o m0trace.*
